Repository NOW-SOPT-CDSP-TEAM-WEB2/Client, pull requests merged in 2024-05, with the labels that each got.

#2 [init/#1] Stylelint 초기세팅
  .stylelintrc
  package.json
  yarn.lock
Labels: 🪡 Init, 상아

#4 [init/#3] ESLint & Prettier 초기설정
  .eslintrc.cjs
  .eslintrc.json
  .prettierrc
  package.json
  src/components/commons/Button.tsx
  yarn.lock
Labels: 🪡 Init, 규홍

#6 [Init/#5] globalStyle, theme 초기세팅
  .eslintrc.json
  index.html
  package.json
  src/App.tsx
  src/Router.tsx
  src/main.tsx
  src/pages/main/main.tsx
  src/styles/globalStyle.ts
  src/styles/style.d.ts
  src/styles/test.tsx
  src/styles/theme.ts
  yarn.lock
Labels: 🪡 Init, 서진

#8 [Feat/#7] 공통 헤더 구현
  package.json
  src/assets/constants/headerDropdown.ts
  src/assets/svgs/ic_hamburger_black_12.svg
  src/assets/svgs/ic_internet_black_12.svg
  src/assets/svgs/index.ts
  src/assets/svgs/index.tsx
  src/assets/svgs/logo.svg
  src/assets/svgs/profileImg.svg
  src/components/commons/Button.tsx
  src/components/commons/Header.tsx
  src/components/commons/HeaderProfile.tsx
  src/components/commons/HomeHeaderContent.tsx
  src/components/commons/NavHeaderContent.tsx
  src/custom.d.ts
  src/hooks/useClickOutside.tsx
  src/pages/main/main.tsx
  src/styles/theme.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feat, 서진

#13 [Feat/#10] 공통 footer
  src/assets/constants/footerTag.ts
  src/assets/svgs/copyright.svg
  src/assets/svgs/ic_blog_black_14.svg
  src/assets/svgs/ic_facebook_black_14.svg
  src/assets/svgs/ic_insta_black_14.svg
  src/assets/svgs/ic_naver_black_14.svg
  src/assets/svgs/ic_x_black_14.svg
  src/assets/svgs/index.tsx
  src/components/commons/footer/Footer.tsx
  src/pages/main/main.tsx
Labels: ✨ Feat, 서진

#18 [design/#17] 푸터 position 제거, 반응형 제거
  src/components/commons/footer/Footer.tsx
  src/pages/wishList/WishList.tsx
  src/styles/globalStyle.ts
Labels: 💄 Design, 서진

#26 [Fix/#25] 버셀 배포 에러 수정
  src/components/commons/Header.tsx
  src/pages/main/main.tsx
Labels: ⚙️ Fix, 서진

#30 [feat/#28] axios client 설정
  .gitignore
  src/utils/api.tsx
  src/utils/client.ts
Labels: ✨ Feat, 상아

#27 [Feat/#11] home 페이지 구현
  .eslintrc.json
  .gitignore
  src/Router.tsx
  src/assets/images/california.png
  src/assets/images/index.ts
  src/assets/images/spain.png
  src/assets/svgs/ic_arrow_left_circle_32.svg
  src/assets/svgs/ic_arrow_right_circle_32.svg
  src/assets/svgs/ic_beach_black_18.svg
  src/assets/svgs/ic_beach_gray_18.svg
  src/assets/svgs/ic_design_black_18.svg
  src/assets/svgs/ic_design_gray_18.svg
  src/assets/svgs/ic_hot_black_18.svg
  src/assets/svgs/ic_hot_grey_18.svg
  src/assets/svgs/ic_park_black_18.svg
  src/assets/svgs/ic_park_gray_18.svg
  src/assets/svgs/ic_search_mini_white_12.svg
  src/assets/svgs/ic_swimming_pool_black_18.svg
  src/assets/svgs/ic_swimming_pool_gray_18.svg
  src/assets/svgs/ic_ufo_black_18.svg
  src/assets/svgs/ic_ufo_gray_18.svg
  src/assets/svgs/index.tsx
  src/components/commons/Header.tsx
  src/components/commons/HomeHeaderContent.tsx
  src/components/commons/NavHeaderContent.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/Card.tsx
  src/pages/HomePage/components/CarouselWrapperList.tsx
  src/pages/HomePage/components/Chips.tsx
  src/pages/HomePage/components/HomeCategorySearch.tsx
  src/pages/HomePage/components/HomeFooter.tsx
  src/pages/HomePage/components/LnbList.tsx
  src/pages/HomePage/components/SearchTravel.tsx
  src/pages/HomePage/constants/index.ts
  src/pages/HomePage/hooks/useScrollY.tsx
Labels: ✨ Feat, 규홍

#19 [Feat/#9] 예약 요청 뷰 구현
  .env
  .stylelintrc
  src/Router.tsx
  src/assets/svgs/SendingMessagetoHost.svg
  src/assets/svgs/ic_amex_normal_24.svg
  src/assets/svgs/ic_arrow_down.svg
  src/assets/svgs/ic_arrow_left_black_24.svg
  src/assets/svgs/ic_diamond_pink_24.svg
  src/assets/svgs/ic_mastercard_normal_24.svg
  src/assets/svgs/ic_mastercard_normal_32.svg
  src/assets/svgs/ic_medal_fill_black_10.svg
  src/assets/svgs/ic_naverpay_normal_24.svg
  src/assets/svgs/ic_star.svg
  src/assets/svgs/ic_time_pink_32.svg
  src/assets/svgs/ic_visa_normal_24.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/postReservation_housingCard.svg
  src/pages/postReservation/PostReservationPage.tsx
  src/pages/postReservation/components/header/postReservationHeader.tsx
  src/pages/postReservation/components/left_side/CardNotice.tsx
  src/pages/postReservation/components/left_side/PaymentWay.tsx
  src/pages/postReservation/components/left_side/PostButton.tsx
  src/pages/postReservation/components/left_side/RefundPolicy.tsx
  src/pages/postReservation/components/left_side/ReserveInfo.tsx
  src/pages/postReservation/components/left_side/SelectPayment.tsx
  src/pages/postReservation/components/left_side/SendingMessage.tsx
  src/pages/postReservation/components/left_side/WrapLeftComponents.tsx
  src/pages/postReservation/components/right_side/AccomodationCard.tsx
  src/pages/postReservation/components/right_side/InfoReservationCard.tsx
  src/pages/postReservation/constatnts/apiTestText.ts
  src/pages/postReservation/constatnts/postResevationText.ts
  src/pages/postReservation/hooks/useExtractDate.tsx
  src/pages/postReservation/utils/extractMonthAndDay.ts
  src/pages/postReservation/utils/getDifferenceDate.ts
  src/pages/postReservation/utils/getPaymentDay.ts
  src/pages/postReservation/utils/getPrice.ts
  src/pages/postReservation/utils/getRefundDate.ts
  src/pages/postReservation/utils/postReserveInfo.ts
Labels: ✨ Feat, 상아

#24 [Feat/#20] 캐러셀 구현
  package.json
  src/Router.tsx
  src/assets/svgs/ic_btn_circle_left.svg
  src/assets/svgs/ic_btn_circle_right.svg
  src/assets/svgs/ic_carousel_star.svg
  src/assets/svgs/ic_heart_pink_24.svg
  src/assets/svgs/index.tsx
  src/components/commons/carousel/CarouselWrapperComponent.tsx
  src/components/commons/carousel/carouselComponent/Carousel.tsx
  src/components/commons/carousel/carouselComponent/CustonArrows.tsx
  src/components/commons/carousel/carouselComponent/css/slick-theme.css
  src/components/commons/carousel/carouselComponent/css/slick.css
  src/components/commons/carousel/components/CarouselText.tsx
  src/components/commons/carousel/components/HeartComponent.tsx
  src/components/commons/carousel/components/SuperHostCard.tsx
  src/components/commons/carousel/constants/apiTest.ts
  yarn.lock
Labels: ✨ Feat, 상아

#23 [Feat/#22] 숙소 상세 하단 뷰
  .env
  src/Router.tsx
  src/assets/svgs/host_info_detail.svg
  src/assets/svgs/host_mark.svg
  src/assets/svgs/host_profile.svg
  src/assets/svgs/index.tsx
  src/assets/svgs/leaf_left.svg
  src/assets/svgs/leaf_right.svg
  src/assets/svgs/pay_warn.svg
  src/assets/svgs/rate_list.svg
  src/assets/svgs/review_list.svg
  src/assets/svgs/share_host.svg
  src/assets/svgs/star.svg
  src/pages/stayDetail/components/HostDetail.tsx
  src/pages/stayDetail/components/Location.tsx
  src/pages/stayDetail/components/Review.tsx
  src/pages/stayDetail/components/StayDetail.tsx
  src/styles/theme.ts
Labels: ✨ Feat, 서진

#21 [Feat/#16] 위시 상세 뷰
  index.html
  package.json
  src/Router.tsx
  src/assets/svgs/btn_ic_circle_pin_amall.svg
  src/assets/svgs/ic_arrow_left_black_wish_detail.svg
  src/assets/svgs/ic_meatball_black_24.svg
  src/assets/svgs/ic_share_black_24.svg
  src/assets/svgs/index.tsx
  src/pages/wishListDetail/WishListDetail.tsx
  src/pages/wishListDetail/components/LocationMarker.tsx
  src/pages/wishListDetail/components/StayLocationMap.tsx
  src/pages/wishListDetail/constants/wishListDetailData.ts
  src/pages/wishListDetail/types/wishListDetailTypes.ts
  tsconfig.json
  yarn.lock
Labels: ✨ Feat, 서진

#34 [Feat/#33] 위시리스트, 위시상세 api 연결
  src/Router.tsx
  src/assets/svgs/ic_heart_pink_24.svg
  src/components/commons/carousel/CarouselWrapperComponent.tsx
  src/components/commons/carousel/CarouselWrapperComponentWish.tsx
  src/components/commons/carousel/carouselComponent/Carousel.tsx
  src/components/commons/carousel/components/CarouselText.tsx
  src/components/commons/carousel/constants/apiTest.ts
  src/components/commons/header/HeaderProfile.tsx
  src/pages/wishList/WishList.tsx
  src/pages/wishList/utils/getWishList.ts
  src/pages/wishListDetail/WishListDetail.tsx
  src/pages/wishListDetail/components/CarouselWrapper.tsx
  src/pages/wishListDetail/components/StayLocationMap.tsx
Labels: ✨ Feat, 서진

#35 [Feat/#32] home api 연결~
  src/assets/svgs/ic_heart_gray_24.svg
  src/assets/svgs/index.tsx
  src/components/commons/carousel/CarouselWrapperComponent.tsx
  src/components/commons/carousel/components/HeartComponent.tsx
  src/components/commons/carousel/constants/apiTest.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/apis/https.ts
  src/pages/HomePage/components/Card.tsx
  src/pages/HomePage/components/CarouselWrapperList.tsx
  src/pages/HomePage/types/HomePageItemType.ts
  src/pages/postReservation/PostReservationPage.tsx
  src/pages/postReservation/utils/postReserveInfo.ts
Labels: ✨ Feat, 규홍

#36 [Feat/#12] 숙소 상세 뷰 상단 영역
  package.json
  src/Router.tsx
  src/assets/svgs/divider.svg
  src/assets/svgs/ic_arrow_below_black_18.svg
  src/assets/svgs/ic_arrow_right_black_14.svg
  src/assets/svgs/ic_baby_non_gray_18.svg
  src/assets/svgs/ic_badge_line_black_24.svg
  src/assets/svgs/ic_bento_black_12.svg
  src/assets/svgs/ic_calendar_black_24.svg
  src/assets/svgs/ic_car_black_18.svg
  src/assets/svgs/ic_carbon_alarm_non_gray_18.svg
  src/assets/svgs/ic_clock_black_32.svg
  src/assets/svgs/ic_diamond_pink_32.svg
  src/assets/svgs/ic_dog_non_gray_32.svg
  src/assets/svgs/ic_fire_alarm_non_gray_18.svg
  src/assets/svgs/ic_fire_black_18.svg
  src/assets/svgs/ic_flag_black_12.svg
  src/assets/svgs/ic_heart_pink_14.svg
  src/assets/svgs/ic_key_black_24.svg
  src/assets/svgs/ic_keyboard_black_18.svg
  src/assets/svgs/ic_kitchen_black_18.svg
  src/assets/svgs/ic_leaf_left_black_32.svg
  src/assets/svgs/ic_leaf_right_black_32.svg
  src/assets/svgs/ic_medal_fill_pink_14.svg
  src/assets/svgs/ic_party_non_gray_32.svg
  src/assets/svgs/ic_people_black_32.svg
  src/assets/svgs/ic_share_black_14.svg
  src/assets/svgs/ic_smoke_non_gray_32.svg
  src/assets/svgs/ic_star_black_8.svg
  src/assets/svgs/ic_tv_non_gray_18.svg
  src/assets/svgs/index.tsx
  src/pages/postReservation/components/header/postReservationHeader.tsx
  src/pages/postReservation/components/left_side/CardNotice.tsx
  src/pages/postReservation/components/left_side/PaymentWay.tsx
  src/pages/postReservation/components/left_side/RefundPolicy.tsx
  src/pages/postReservation/components/left_side/ReserveInfo.tsx
  src/pages/postReservation/components/left_side/SelectPayment.tsx
  src/pages/postReservation/components/left_side/SendingMessage.tsx
  src/pages/postReservation/components/left_side/WrapLeftComponents.tsx
  src/pages/postReservation/components/right_side/InfoReservationCard.tsx
  src/pages/stayDetail/StayDetailPage.tsx
  src/pages/stayDetail/components/Divider.tsx
  src/pages/stayDetail/components/InputCalendar.tsx
  src/pages/stayDetail/components/OutputCalendar.tsx
  src/pages/stayDetail/components/StayCalendar.tsx
  src/pages/stayDetail/components/StayFacility.tsx
  src/pages/stayDetail/components/StayHeader.tsx
  src/pages/stayDetail/components/StayInfo.tsx
  src/pages/stayDetail/components/StayReserve.tsx
  src/pages/stayDetail/components/StayRule.tsx
  src/pages/stayDetail/constants.ts
  src/pages/stayDetail/types/getStayDetailType.ts
  src/pages/stayDetail/utils/getDateInKor.tsx
  src/pages/stayDetail/utils/getFreeCancelationDate.tsx
  src/pages/stayDetail/utils/getStayDate.tsx
  src/pages/stayDetail/utils/stayFee.tsx
  src/utils/api.tsx
  yarn.lock
Labels: ✨ Feat, 지민

#38 [Feat/#37] 숙소 상세 뷰 합치기, 예약요청에 데이터 전달
  package.json
  src/Router.tsx
  src/pages/postReservation/components/right_side/InfoReservationCard.tsx
  src/pages/stayDetail/StayDetailCombine.tsx
  src/pages/stayDetail/StayDetailPage.tsx
  src/pages/stayDetail/components/InputCalendar.tsx
  src/pages/stayDetail/components/Layout.tsx
  src/pages/stayDetail/components/Location.tsx
  src/pages/stayDetail/components/StayCalendar.tsx
  src/pages/stayDetail/components/StayInfo.tsx
  src/pages/stayDetail/components/StayMap.tsx
  src/pages/stayDetail/components/StayReserve.tsx
  src/pages/stayDetail/utils/stayFee.tsx
  yarn.lock
Labels: ✨ Feat, 서진
